# -*- coding: utf-8 -*-
"""Control Structures.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hLMHhNIoYrBkcdfvMqfBAnJKnKT97w_x
"""

clean_car_red = True
clean_car_blue = True
clean_car_green = True
num_of_car = 0
busy = False

print("Welcome to the car wash")

redCheck = input("Is the Red car Dirty? (Yes or No)") #Note input is case sensitive here
if redCheck == "Yes":
	clean_car_red = False

blueCheck = input("Is the Blue car Dirty? (Yes or No)") #Note input is case sensitive here
if blueCheck == "Yes":
	clean_car_blue = False

greenCheck = input("Is the Green car Dirty? (Yes or No)") #Note input is case sensitive here
if greenCheck == "Yes":
	clean_car_green = False

if clean_car_red == False:
	print("Red car really needs a cleaning")
	num_of_car += 1

if clean_car_blue == False:
	print("Blue car really needs a cleaning")
	num_of_car += 1

if clean_car_green == False:
	print("Green car really needs a cleaning")
	num_of_car += 1
	print(num_of_car)

if num_of_car == 3:
	busy = True

name = input("Enter your name: \n")

if len(name) == 0:
	print ("You didn't enter anything.")

if len(name) > 10:
	print ("You've got a long name.")

print(name)

print ("Example 1: ")
grade = 88

if grade >= 80:
        print ("Congratulations! You have an A")
elif grade >= 70:
        print ("Good job! You have a B")
elif grade >= 60:
        print ("Keep it up! You have a C")
elif grade >= 50:
        print ("Try a little harder next time! You have a D")
else:
        print ("Oh No! You have an F")

num_str = input("Enter a number, or enter 'NO' to stop the program: ")
if num_str == "2":
    num_int = int(num_str)
    #string input was cast to int
    print ("The string '2' was successfully cast to an integer")
elif num_str == "3":
     num_int = int(num_str)
     #string input was cast to int
     print ("The string '3' was successfully cast to an integer")
elif num_str > "3":
      print("I don't know what to do  this number any number higher than 3")
else:
    print ("The word 'NO' can't be cast to an int.")

current_time = 12

if current_time < 11:
  print('Time for a short jog- lets go:')
else:
  print('its after 11 - its lunch time:')

"""#### age-quiz.py"""

Age = int(input('Enter your age:'))

if Age > 40:
  print('You are over the hill')

age = int(input('Enter user age:'))

if age > 100:
  print('sorry you are dead.')
elif age >= 65:
  print('Enjoy your retirement')
elif age < 13:
  print('You qualify for the kiddie discount.')
elif age == 21:
  print('Congrats on your 21st. ')
else:
  print('Age is but a number.')